env:
  browser: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: false
  ecmaFeatures:
    jsx: true
plugins:
- react
- prettier
extends:
- airbnb
- airbnb/hooks
- plugin:prettier/recommended
- prettier
- prettier/react
rules:
  quotes:
  - error
  - single
  no-redeclare: warn
  no-empty: warn
  no-underscore-dangle:
  - error
  - allow:
    - __REDUX_DEVTOOLS_EXTENSION__
  prettier/prettier:
  - error
  react/forbid-prop-types:
  - error
  - forbid:
    - any
  react/jsx-filename-extension:
  - warn
  - extensions:
    - .js
    - .jsx
  react/require-default-props:
  - warn
  max-classes-per-file:
  - error
  - 2
  import/no-named-as-default: off
  no-console: off
  react/destructuring-assignment: off
globals:
  THREE: false
  process: true
settings:
  import/resolver:
    webpack:
      config: webpack.config.js
  react:
    version: detect